export default {
  SET_ROOM: 'SET_ROOM',
  SET_GUESTS: 'SET_GUESTS',
  REMOVE_GUEST: 'REMOVE_GUEST',
  ADD_GUEST: 'ADD_GUEST',
  SET_USER: "SET_USER",
  PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION"
}
